spring:
  thymeleaf:
    mode: HTML
  mvc:
    throw-exception-if-no-handler-found: true
  profiles:
    active: pro
#指定mapper.xml文件的位置，否则编译时找不到文件
mybatis:
  mapper-locations: classpath*:/entityMapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

