spring:


  datasource:
    #8以上版本
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8
    username: root
    password: 123456zts
#日志级别
#logging:
#  level:
#    root: info
#    com.tension.mblog: debug
#  file: log/blog-dev.log

server:
  port: 8081

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml

